### ISSUE TITLE
What is the recommended way of handling sourceMaps?

### ISSUE THREAD

**Issue by kirill-konshin** [gfranko/amdclean#65]
If I run RequireJS optimizer with `generateSourceMaps: true` how to make sure that nothing breaks after AmdClean (which is called from `onModuleBundleComplete`)?

What is a recommended way?

Btw, if I use AmdClean with `wrap`, it kills the line `//# sourceMappingURL=...`.

**Comment by sprat** [comment]
I consider it's a bug if we can't use wrap and generate source maps together. Other tools do exactly that, like uglifyjs2 for example. So, I think the problem should be addressed and this bug reopened.

**Comment by kirill-konshin** [comment]
As stated before, use `gulp-wrap-js` that takes care of source maps and wrapping. I don't think that this particular project needs to handle anything besides cleaning. I propose to remove the wrap option completely to avoid confusion.

**Comment by sprat** [comment]
I've just edited my previous comment...

**Comment by kirill-konshin** [comment]
I saw your edits after I've posted my comment, so I think we are on the same page.

For those who can't use Gulp plugin, you can take a look in its source code, there is nothing special, just use same approach.

**Comment by sprat** [comment]
I'm still annoyed that I have to wrap the code outside of AMDclean, since it's actually . I think it should be easy to fix, given we have all the things we need to do that in amdclean. Conceptually:
1. concatenate wrap.start + a marker + wrap.end
2. generate an AST from that
3. replace the marker node by the amdclean output AST and we should be done.

I'll probably give it a try and submit a pull request if I manage to make it work.

**Comment by kirill-konshin** [comment]
I doubt that code wrapping is the core functionality of AMDclean. I'd rather remove it completely. It is always better to keep the package small and focused.

**Comment by sprat** [comment]
From the maintenance perspective, I agree with you... But we miss a build-tool-agnostic wrapping package, as I stated in a previous comment. See http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/ for a rationale. If such a tool would exist, we could use it directly in amdclean to wrap the generated code.

From the user point of view, I prefer having a single tool doing all I need to do instead of many.

Furthermore, without wrapping, the generated code pollutes the global namespace very much: see #92. So I would do that by default...

**Comment by kirill-konshin** [comment]
If you don't use Grunt/Gulp, then you should take a look on https://github.com/estools/estemplate which is used by `gulp-wrap-js`.

**Comment by sprat** [comment]
Ok, I will have a look on this tool, seems to do exactly what we want to do.

**Comment by kirill-konshin** [comment]
I have another open issue regarding this https://github.com/gfranko/amdclean/issues/65
