### ISSUE TITLE
Creating a module named "document" will overwrite the window's document

### ISSUE THREAD

**Issue by LukasBombach** [gfranko/amdclean#92]
I have created a file `document.js`, which makes sense in my library (WYSIWYG editor). AMD clean creates a variable `document = {}` for this. Now when I want to access the window's document (like `document.createElement`) it will have been overwritten by this variable.

Workaround: For now I use `window.document.createElement`, but I wish I wouldn't have to.

Possible solution: Namespace or prefix the variables created for AMD/CommonJs modules by AMD clean.

**Comment by sprat** [comment]
I think it would be a better idea to namespace the modules:
1. there would be only one variable possibly clashing with the (browser) environment
2. since we already have an object storing the modules configs, we can probably use the same object to store the exported module.

I would generate something like that:
```javascript
var amd_modules={
  'my_module': {
    config: function() {
      return { /*...*/ };
    }
  }
};
amd_modules['my_module'] = function(/*...*/) {
}(/*...*/);
```
If the module use the special `module` dependency, we can pass `modules['my_module']` into the function.

But note that both solutions (namespacing or prefixing) will break existing code not using `globalModules` and relying on the module naming convention. But, I think it's worth changing because the name clash issues are harder to deal with.

**Comment by sprat** [comment]
I've encountered another name clash issue with a module written like this (example.js):

```javascript
(function ($) {
  function example() {
    /* some code here */
  }

  if (typeof define === 'function' && define.amd) {
    define(function () {
      return example;
    });
  } else {
    $.example = example;
  }
}(this));
```

It's converted to:
```javascript
var example;
(function ($) {
  function example() {
    /* some code here */
  }
  if (true) {
    example = function () {
      return example;
    }();
  } else {
    $.example = example;
  }
}(this));
```
As the module name is the same as an internal function name, the generated code is wrong due to the name clash. I really think putting the exported modules in a modules or amd_modules object would be a good idea! I'll try to propose a pull request doing just that.

**Comment by gfranko** [comment]
I think a better solution would be to use the `prefixTransform` option to provide the variable namespace yourself
